services:
  photoprism:
    image: photoprism/photoprism:latest
    container_name: photoprism
    stop_grace_period: 10s
    privileged: true
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    networks:
      - frontend
    ports:
      - "2342:2342"
    environment:
      PHOTOPRISM_ADMIN_USER: ${ADMIN_USER}
      PHOTOPRISM_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      PHOTOPRISM_AUTH_MODE: "password"
      PHOTOPRISM_SITE_URL: "https://${PUBLIC_DOMAIN}/"
      PHOTOPRISM_DISABLE_TLS: "false"
      PHOTOPRISM_DEFAULT_TLS: "true"
      PHOTOPRISM_ORIGINALS_LIMIT: 5000               
      PHOTOPRISM_HTTP_COMPRESSION: "none"
      PHOTOPRISM_LOG_LEVEL: "info"
      PHOTOPRISM_READONLY: "true"
      PHOTOPRISM_EXPERIMENTAL: "true"
      PHOTOPRISM_DISABLE_CHOWN: "true"
      PHOTOPRISM_DISABLE_WEBDAV: "true"
      PHOTOPRISM_DISABLE_SETTINGS: "false"
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"
      PHOTOPRISM_DISABLE_FACES: "false"
      PHOTOPRISM_DISABLE_CLASSIFICATION: "false"
      PHOTOPRISM_DISABLE_VECTORS: "false"
      PHOTOPRISM_DISABLE_RAW: "false"
      PHOTOPRISM_RAW_PRESETS: "false"
      PHOTOPRISM_JPEG_QUALITY: 85                    
      PHOTOPRISM_THUMB_SIZE: 2048
      PHOTOPRISM_DETECT_NSFW: "true"
      PHOTOPRISM_UPLOAD_NSFW: "false"
      PHOTOPRISM_DATABASE_DRIVER: "mysql"
      PHOTOPRISM_DATABASE_SERVER: ${MYSQL_SERVER}
      PHOTOPRISM_DATABASE_NAME: ${MYSQL_NAME}
      PHOTOPRISM_DATABASE_USER: ${MYSQL_USER}
      PHOTOPRISM_DATABASE_PASSWORD: ${MYSQL_PASSWORD}
      PHOTOPRISM_SITE_CAPTION: "AI-Powered Photos App"
      PHOTOPRISM_ORIGINALS_PATH: "/photoprism/originals"
      PHOTOPRISM_SITE_DESCRIPTION: ""
      PHOTOPRISM_SITE_AUTHOR: ""
      PHOTOPRISM_FFMPEG_ENCODER: "intel"
      PHOTOPRISM_FFMPEG_SIZE: "1920"
      PHOTOPRISM_FFMPEG_BITRATE: "32"
      PHOTOPRISM_INIT: "intel"
      PHOTOPRISM_UID: ${PUID}
      PHOTOPRISM_GID: ${PGID}
      PHOTOPRISM_OIDC_URI: "${PHOTOPRISM_OIDC_URI}"
      PHOTOPRISM_OIDC_CLIENT: "${PHOTOPRISM_OIDC_CLIENT}"
      PHOTOPRISM_OIDC_SECRET: "${PHOTOPRISM_OIDC_SECRET}"
      PHOTOPRISM_OIDC_PROVIDER: "authentik"
      PHOTOPRISM_OIDC_REDIRECT: "true"
      PHOTOPRISM_OIDC_REGISTER: "true"
      PHOTOPRISM_OIDC_ICON: "/static/img/oidc.svg"
    user: "${PUID}:${PGID}"
    devices:
      - "/dev/dri:/dev/dri"
    working_dir: "/photoprism"
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.routers.photoprism.rule=Host(`${PUBLIC_DOMAIN}`)
      - traefik.http.routers.photoprism.entrypoints=websecure
      - traefik.http.routers.photoprism.tls=true
      - traefik.http.services.photoprism-service.loadbalancer.server.port=2342
    volumes:
      - ${MOUNT_ROOT}/photoprism:/photoprism/storage
      - ${MOUNT_ROOT_VIDEOS}:/photoprism/originals/Videos:ro
      - ${MOUNT_ROOT_PHOTOSYNC}:/photoprism/originals/PhotoSync:ro
      - ${MOUNT_ROOT_PICTURES}:/photoprism/originals/Bilder:ro
    deploy:
      resources:
        limits:
          cpus: '2'

networks:
  frontend:
    external: true
